export default [
 { name: "align-content", desc: "Aligne le contenu d'un conteneur flexible lorsque les éléments ne prennent pas tout l'espace disponible." },
 { name: "align-items", desc: "Aligne les éléments flexibles le long de l'axe transversal." },
 { name: "align-self", desc: "Aligne un élément flexible individuel le long de l'axe transversal." },
 { name: "animation", desc: "Définit une animation CSS." },
 { name: "animation-delay", desc: "Définit le délai avant le début d'une animation." },
 { name: "animation-direction", desc: "Définit la direction d'une animation." },
 { name: "animation-duration", desc: "Définit la durée d'une animation." },
 { name: "animation-fill-mode", desc: "Définit le style d'un élément lorsque l'animation n'est pas en cours." },
 { name: "animation-iteration-count", desc: "Définit le nombre de répétitions d'une animation." },
 { name: "animation-name", desc: "Définit le nom d'une animation." },
 { name: "animation-play-state", desc: "Définit si une animation est en cours ou en pause." },
 { name: "animation-timing-function", desc: "Définit la vitesse d'une animation." },
 { name: "backface-visibility", desc: "Définit si la face arrière d'un élément est visible lorsqu'il est tourné." },
 { name: "background", desc: "Définit les propriétés d'arrière-plan en une seule déclaration." },
 { name: "background-attachment", desc: "Définit si l'arrière-plan est fixe ou défile avec la page." },
 { name: "background-blend-mode", desc: "Définit comment mélanger chaque arrière-plan." },
 { name: "background-clip", desc: "Définit la zone d'étendue de l'arrière-plan." },
 { name: "background-color", desc: "Définit la couleur d'arrière-plan d'un élément." },
 { name: "background-image", desc: "Définit une ou plusieurs images d'arrière-plan." },
 { name: "background-origin", desc: "Définit l'origine de l'arrière-plan." },
 { name: "background-position", desc: "Définit la position initiale de l'image d'arrière-plan." },
 { name: "background-repeat", desc: "Définit si l'image d'arrière-plan se répète ou non." },
 { name: "background-size", desc: "Définit la taille des images d'arrière-plan." },
 { name: "border", desc: "Définit toutes les propriétés de bordure en une seule déclaration." },
 { name: "border-bottom", desc: "Définit la bordure inférieure d'un élément." },
 { name: "border-bottom-color", desc: "Définit la couleur de la bordure inférieure." },
 { name: "border-bottom-left-radius", desc: "Définit le rayon de bordure inférieur gauche." },
 { name: "border-bottom-right-radius", desc: "Définit le rayon de bordure inférieur droit." },
 { name: "border-bottom-style", desc: "Définit le style de la bordure inférieure." },
 { name: "border-bottom-width", desc: "Définit la largeur de la bordure inférieure." },
 { name: "border-collapse", desc: "Définit si les bordures du tableau doivent être fusionnées." },
 { name: "border-color", desc: "Définit la couleur des quatre bordures." },
 { name: "border-image", desc: "Définit une image à utiliser comme bordure." },
 { name: "border-image-outset", desc: "Définit la distance par laquelle la bordure image s'étend." },
 { name: "border-image-repeat", desc: "Définit si l'image bordure doit être répétée ou étirée." },
 { name: "border-image-slice", desc: "Définit comment découper l'image bordure." },
 { name: "border-image-source", desc: "Définit le chemin de l'image bordure." },
 { name: "border-image-width", desc: "Définit la largeur de l'image bordure." },
 { name: "border-left", desc: "Définit la bordure gauche d'un élément." },
 { name: "border-left-color", desc: "Définit la couleur de la bordure gauche." },
 { name: "border-left-style", desc: "Définit le style de la bordure gauche." },
 { name: "border-left-width", desc: "Définit la largeur de la bordure gauche." },
 { name: "border-radius", desc: "Définit les coins arrondis d'un élément." },
 { name: "border-right", desc: "Définit la bordure droite d'un élément." },
 { name: "border-right-color", desc: "Définit la couleur de la bordure droite." },
 { name: "border-right-style", desc: "Définit le style de la bordure droite." },
 { name: "border-right-width", desc: "Définit la largeur de la bordure droite." },
 { name: "border-spacing", desc: "Définit l'espace entre les bordures des cellules de tableau." },
 { name: "border-style", desc: "Définit le style des quatre bordures." },
 { name: "border-top", desc: "Définit la bordure supérieure d'un élément." },
 { name: "border-top-color", desc: "Définit la couleur de la bordure supérieure." },
 { name: "border-top-left-radius", desc: "Définit le rayon de bordure supérieur gauche." },
 { name: "border-top-right-radius", desc: "Définit le rayon de bordure supérieur droit." },
 { name: "border-top-style", desc: "Définit le style de la bordure supérieure." },
 { name: "border-top-width", desc: "Définit la largeur de la bordure supérieure." },
 { name: "border-width", desc: "Définit la largeur des quatre bordures." },
 { name: "bottom", desc: "Définit la position inférieure d'un élément positionné." },
 { name: "box-shadow", desc: "Ajoute une ou plusieurs ombres à un élément." },
 { name: "box-sizing", desc: "Définit si la largeur et la hauteur incluent le padding et la bordure." },
 { name: "break-after", desc: "Définit comment la page doit se comporter après un élément." },
 { name: "break-before", desc: "Définit comment la page doit se comporter avant un élément." },
 { name: "break-inside", desc: "Définit comment la page doit se comporter à l'intérieur d'un élément." },
 { name: "caption-side", desc: "Définit le positionnement de la légende du tableau." },
 { name: "caret-color", desc: "Définit la couleur du curseur de texte." },
 { name: "clear", desc: "Définit ce qui peut flotter de chaque côté d'un élément." },
 { name: "clip", desc: "Découpe un élément positionné absolument." },
 { name: "color", desc: "Définit la couleur de premier plan d'un élément texte et de ses éventuelles décorations." },
 { name: "column-count", desc: "Définit le nombre de colonnes dans lequel le contenu doit être divisé." },
 { name: "column-fill", desc: "Définit comment remplir les colonnes." },
 { name: "column-gap", desc: "Définit l'espace entre les colonnes." },
 { name: "column-rule", desc: "Définit toutes les propriétés de règle de colonne en une seule déclaration." },
 { name: "column-rule-color", desc: "Définit la couleur de la règle de colonne." },
 { name: "column-rule-style", desc: "Définit le style de la règle de colonne." },
 { name: "column-rule-width", desc: "Définit la largeur de la règle de colonne." },
 { name: "column-span", desc: "Définit combien de colonnes un élément doit traverser." },
 { name: "column-width", desc: "Définit la largeur des colonnes." },
 { name: "columns", desc: "Définit le nombre et le style des colonnes." },
 { name: "content", desc: "Utilisé avec les pseudo-éléments ::before et ::after pour insérer du contenu généré." },
 { name: "counter-increment", desc: "Incrémente un compteur CSS." },
 { name: "counter-reset", desc: "Réinitialise un compteur CSS." },
 { name: "cursor", desc: "Définit le type de curseur à afficher." },
 { name: "direction", desc: "Définit la direction du texte." },
 { name: "display", desc: "Définit le type de rendu d'un élément." },
 { name: "empty-cells", desc: "Définit si les bordures et l'arrière-plan des cellules vides doivent être affichés." },
 { name: "filter", desc: "Définit les effets visuels (comme le flou ou la saturation)." },
 { name: "flex", desc: "Définit un conteneur flexible." },
 { name: "flex-basis", desc: "Définit la taille par défaut d'un élément flexible." },
 { name: "flex-direction", desc: "Définit la direction des éléments flexibles." },
 { name: "flex-flow", desc: "Définit l'ordre et la direction des éléments flexibles." },
 { name: "flex-grow", desc: "Définit la croissance d'un élément flexible." },
 { name: "flex-shrink", desc: "Définit la réduction d'un élément flexible." },
 { name: "flex-wrap", desc: "Définit si les éléments flexibles doivent envelopper ou non." },
 { name: "float", desc: "Définit le positionnement flottant d'un élément." },
 { name: "font", desc: "Définit toutes les propriétés de police en une seule déclaration." },
 { name: "font-family", desc: "Définit la famille de police d'un texte." },
 { name: "font-feature-settings", desc: "Contrôle les fonctionnalités OpenType." },
 { name: "font-kerning", desc: "Contrôle le crénage de la police." },
 { name: "font-size", desc: "Définit la taille de la police." },
 { name: "font-size-adjust", desc: "Conserve la lisibilité de la police lors de la modification de la taille." },
 { name: "font-stretch", desc: "Définit l'étirement de la police." },
 { name: "font-style", desc: "Définit le style de la police." },
 { name: "font-variant", desc: "Contrôle les variantes de texte et de chiffres." },
 { name: "font-variant-caps", desc: "Contrôle les variantes de capitalisation." },
 { name: "font-variant-ligatures", desc: "Contrôle les ligatures contextuelles et discrétionnaires." },
 { name: "font-variant-numeric", desc: "Contrôle les variantes numériques." },
 { name: "font-weight", desc: "Définit l'épaisseur de la police." },
 { name: "gap", desc: "Définit l'espace entre les éléments d'une grille ou d'un conteneur flexible." },
 { name: "grid", desc: "Définit un conteneur de grille." },
 { name: "grid-area", desc: "Définit une zone de grille." },
 { name: "grid-auto-columns", desc: "Définit une taille par défaut pour les colonnes de la grille." },
 { name: "grid-auto-flow", desc: "Définit comment les éléments automatiquement placés doivent remplir la grille." },
 { name: "grid-auto-rows", desc: "Définit une taille par défaut pour les lignes de la grille." },
 { name: "grid-column", desc: "Définit sur quelle colonne un élément de grille doit commencer et finir." },
 { name: "grid-column-end", desc: "Définit la fin d'un élément de grille." },
 { name: "grid-column-gap", desc: "Définit l'espace entre les colonnes de la grille." },
 { name: "grid-column-start", desc: "Définit le début d'un élément de grille." },
 { name: "grid-gap", desc: "Définit l'espace entre les lignes et colonnes de la grille." },
 { name: "grid-row", desc: "Définit sur quelle ligne un élément de grille doit commencer et finir." },
 { name: "grid-row-end", desc: "Définit la fin d'un élément de grille." },
 { name: "grid-row-gap", desc: "Définit l'espace entre les lignes de la grille." },
 { name: "grid-row-start", desc: "Définit le début d'un élément de grille." },
 { name: "grid-template", desc: "Définit les colonnes, lignes et zones d'une grille." },
 { name: "grid-template-areas", desc: "Définit les zones nommées dans une grille." },
 { name: "grid-template-columns", desc: "Définit les colonnes d'une grille." },
 { name: "grid-template-rows", desc: "Définit les lignes d'une grille." },
 { name: "hanging-punctuation", desc: "Définit si une ponctuation peut être placée en dehors de la boîte d'un élément." },
 { name: "height", desc: "Définit la hauteur d'un élément." },
 { name: "hyphens", desc: "Définit comment les mots doivent être coupés lorsqu'ils dépassent de la zone de contenu." },
 { name: "isolation", desc: "Définit si un élément doit créer un nouveau contexte d'empilement." },
 { name: "justify-content", desc: "Aligne les éléments flexibles le long de l'axe principal." },
 { name: "left", desc: "Définit la position gauche d'un élément positionné." },
 { name: "letter-spacing", desc: "Définit l'espacement entre les caractères d'un texte." },
 { name: "line-break", desc: "Définit comment le texte doit se comporter lorsqu'il atteint la fin d'une ligne." },
 { name: "line-height", desc: "Définit la hauteur des lignes de texte." },
 { name: "list-style", desc: "Définit toutes les propriétés de style de liste en une seule déclaration." },
 { name: "list-style-image", desc: "Définit une image comme marqueur de liste." },
 { name: "list-style-position", desc: "Définit la position des marqueurs de liste." },
 { name: "list-style-type", desc: "Définit le type de marqueur de liste." },
 { name: "margin", desc: "Définit toutes les marges en une seule déclaration." },
 { name: "margin-bottom", desc: "Définit la marge inférieure d'un élément." },
 { name: "margin-left", desc: "Définit la marge gauche d'un élément." },
 { name: "margin-right", desc: "Définit la marge droite d'un élément." },
 { name: "margin-top", desc: "Définit la marge supérieure d'un élément." },
 { name: "max-height", desc: "Définit la hauteur maximale d'un élément." },
 { name: "max-width", desc: "Définit la largeur maximale d'un élément." },
 { name: "min-height", desc: "Définit la hauteur minimale d'un élément." },
 { name: "min-width", desc: "Définit la largeur minimale d'un élément." },
 { name: "mix-blend-mode", desc: "Définit comment une image doit se mélanger avec l'arrière-plan." },
 { name: "object-fit", desc: "Définit comment un élément rempli doit être ajusté." },
 { name: "object-position", desc: "Définit la position d'un élément rempli." },
 { name: "opacity", desc: "Définit le niveau de transparence d'un élément." },
 { name: "order", desc: "Définit l'ordre des éléments flexibles." },
 { name: "orphans", desc: "Définit le nombre minimum de lignes dans un élément en haut d'une page." },
 { name: "outline", desc: "Définit toutes les propriétés de contour en une seule déclaration." },
 { name: "outline-color", desc: "Définit la couleur du contour." },
 { name: "outline-offset", desc: "Définit l'espace entre un contour et le bord d'un élément." },
 { name: "outline-style", desc: "Définit le style du contour." },
 { name: "outline-width", desc: "Définit la largeur du contour." },
 { name: "overflow", desc: "Définit ce qui se passe si le contenu dépasse la boîte d'un élément." },
 { name: "overflow-wrap", desc: "Définit si le navigateur doit insérer un retour à la ligne." },
 { name: "overflow-x", desc: "Définit le débordement horizontal." },
 { name: "overflow-y", desc: "Définit le débordement vertical." },
 { name: "padding", desc: "Définit toutes les propriétés de remplissage en une seule déclaration." },
 { name: "padding-bottom", desc: "Définit le remplissage inférieur d'un élément." },
 { name: "padding-left", desc: "Définit le remplissage gauche d'un élément." },
 { name: "padding-right", desc: "Définit le remplissage droit d'un élément." },
 { name: "padding-top", desc: "Définit le remplissage supérieur d'un élément." },
 { name: "page-break-after", desc: "Définit si une rupture de page doit être insérée après un élément." },
 { name: "page-break-before", desc: "Définit si une rupture de page doit être insérée avant un élément." },
 { name: "page-break-inside", desc: "Définit si une rupture de page est autorisée à l'intérieur d'un élément." },
 { name: "perspective", desc: "Définit la distance entre le spectateur et la scène 3D." },
 { name: "perspective-origin", desc: "Définit la position de base de la perspective." },
 { name: "pointer-events", desc: "Définit si un élément réagit aux événements de la souris." },
 { name: "position", desc: "Définit le type de positionnement d'un élément." },
 { name: "quotes", desc: "Définit le style des guillemets." },
 { name: "resize", desc: "Définit si un élément est redimensionnable par l'utilisateur." },
 { name: "right", desc: "Définit la position droite d'un élément positionné." },
 { name: "row-gap", desc: "Définit l'espace entre les lignes d'une grille." },
 { name: "scroll-behavior", desc: "Définit le comportement de défilement pour un élément défilant." },
 { name: "tab-size", desc: "Définit la largeur des tabulations." },
 { name: "table-layout", desc: "Définit l'algorithme de disposition à utiliser pour un tableau." },
 { name: "text-align", desc: "Définit l'alignement horizontal d'un texte." },
 { name: "text-align-last", desc: "Définit comment aligner la dernière ligne d'un bloc ou d'une ligne." },
 { name: "text-combine-upright", desc: "Définit la combinaison de caractères dans un texte vertical." },
 { name: "text-decoration", desc: "Définit toutes les décorations de texte en une seule déclaration." },
 { name: "text-decoration-color", desc: "Définit la couleur des décorations de texte." },
 { name: "text-decoration-line", desc: "Définit le type de décoration de texte." },
 { name: "text-decoration-style", desc: "Définit le style des décorations de texte." },
 { name: "text-indent", desc: "Définit l'indentation de la première ligne d'un texte." },
 { name: "text-justify", desc: "Définit le justifié du texte lorsqu'il est aligné." },
 { name: "text-overflow", desc: "Définit comment le texte dépassant doit être signalé à l'utilisateur." },
 { name: "text-shadow", desc: "Ajoute une ombre au texte." },
 { name: "text-transform", desc: "Contrôle la capitalisation du texte." },
 { name: "top", desc: "Définit la position supérieure d'un élément positionné." },
 { name: "transform", desc: "Applique une transformation 2D ou 3D à un élément." },
 { name: "transform-origin", desc: "Définit l'origine de la transformation d'un élément." },
 { name: "transform-style", desc: "Définit comment les éléments imbriqués sont rendus en 3D." },
 { name: "transition", desc: "Définit une transition entre deux états d'un élément." },
 { name: "transition-delay", desc: "Définit le délai avant le début d'une transition." },
 { name: "transition-duration", desc: "Définit la durée d'une transition." },
 { name: "transition-property", desc: "Définit la propriété CSS à laquelle la transition s'applique." },
 { name: "transition-timing-function", desc: "Définit la vitesse d'une transition." },
 { name: "unicode-bidi", desc: "Définit le niveau d'intégration du texte lorsqu'il est mélangé avec du texte d'une autre direction." },
 { name: "user-select", desc: "Définit si le texte peut être sélectionné par l'utilisateur." },
 { name: "vertical-align", desc: "Définit l'alignement vertical d'un élément." },
 { name: "visibility", desc: "Définit la visibilité d'un élément." },
 { name: "white-space", desc: "Définit comment l'espace blanc à l'intérieur d'un élément est géré." },
 { name: "widows", desc: "Définit le nombre minimum de lignes dans un élément en bas d'une page." },
 { name: "width", desc: "Définit la largeur d'un élément." },
 { name: "will-change", desc: "Permet aux auteurs de informer le navigateur de quelles propriétés vont changer." },
 { name: "word-break", desc: "Définit comment les mots doivent être coupés lorsqu'ils dépassent de la zone de contenu." },
 { name: "word-spacing", desc: "Définit l'espacement entre les mots d'un texte." },
 { name: "word-wrap", desc: "Définit si le navigateur peut insérer un retour à la ligne au milieu d'un mot." },
 { name: "writing-mode", desc: "Définit si le texte est horizontal ou vertical." },
 { name: "z-index", desc: "Définit l'ordre d'empilement d'un élément positionné." }
]