export default [
  { "q": "a", "desc": "Lien hypertexte." },
  { "q": "abbr", "desc": "Abréviation ou acronyme." },
  { "q": "address", "desc": "Informations de contact." },
  { "q": "article", "desc": "Contenu indépendant et autonome." },
  { "q": "aside", "desc": "Contenu indirectement lié au contenu principal." },
  { "q": "audio", "desc": "Intégrer des contenus audio." },
  { "q": "b", "desc": "Texte pour attirer l'attention, sans (non sémantique)." },
  { "q": "blockquote", "desc": "Citation étendue d'une autre source." },
  { "q": "body", "desc": "Contenu du document." },
  { "q": "br", "desc": "Saut de ligne." },
  { "q": "button", "desc": "Bouton cliquable." },
  { "q": "canvas", "desc": "Dessiner des graphiques via des scripts." },
  { "q": "caption", "desc": "Titre d'un tableau." },
  { "q": "code", "desc": "Extrait de code informatique." },
  { "q": "col", "desc": "Définition d'une colonne dans un tableau" },
  { "q": "colgroup", "desc": "Groupe de colonnes d'un tableau." },
  { "q": "data", "desc": "Valeur de données lisibles par machine." },
  { "q": "datalist", "desc": "Liste de suggestions pour un champ de saisie." },
  { "q": "dd", "desc": "Définition d'un terme." },
  { "q": "del", "desc": "Partie de texte qui a été supprimée." },
  { "q": "details", "desc": "Section déroulante interactive." },
  { "q": "dfn", "desc": "Définir un terme." },
  { "q": "dialog", "desc": "Boîte de dialogue." },
  { "q": "div", "desc": "Section générique de contenu." },
  { "q": "dl", "desc": "Liste de descriptions." },
  { "q": "dt", "desc": "Terme dans une liste de description." },
  { "q": "em", "desc": "Texte avec mise en avant." },
  { "q": "embed", "desc": "Intégration de contenu externe." },
  { "q": "fieldset", "desc": "Groupe de champs de formulaire." },
  { "q": "figcaption", "desc": "Légende d'une figure." },
  { "q": "figure", "desc": "Regroupement de contenu illustratif." },
  { "q": "footer", "desc": "Pied de page ou de section." },
  { "q": "form", "desc": "Formulaire." },
  { "q": "h1", "desc": "Titre principal de page ou de section." },
  { "q": "h2", "desc": "Sous-titre de niveau 2." },
  { "q": "h3", "desc": "Sous-titre de niveau 3." },
  { "q": "h4", "desc": "Sous-titre de niveau 4." },
  { "q": "h5", "desc": "Sous-titre de niveau 5." },
  { "q": "h6", "desc": "Sous-titre de niveau 6." },
  { "q": "head", "desc": "Informations sur le document." },
  { "q": "header", "desc": "En-tête de page ou de section." },
  { "q": "hgroup", "desc": "Groupe de titres." },
  { "q": "hr", "desc": "Séparation thématique entre les paragraphes." },
  { "q": "html", "desc": "Élément racine d'un document HTML." },
  { "q": "i", "desc": "Texte qui se différencie du texte principal (non sémantique)." },
  { "q": "iframe", "desc": "Cadre intégré." },
  { "q": "img", "desc": "Image." },
  { "q": "input", "desc": "Champ de saisie dans un formulaire." },
  { "q": "ins", "desc": "Texte inséré." },
  { "q": "kbd", "desc": "Entrée clavier." },
  { "q": "label", "desc": "Étiquette pour un champ de formulaire." },
  { "q": "legend", "desc": "Légende pour un groupe de champs de formulaire." },
  { "q": "li", "desc": "Élément dans une liste." },
  { "q": "link", "desc": "Relation à une ressource externe." },
  { "q": "main", "desc": "Contenu principal d'un document." },
  { "q": "map", "desc": "Carte d'image." },
  { "q": "mark", "desc": "Texte en évidence." },
  { "q": "meta", "desc": "Métadonnées pour le document." },
  { "q": "meter", "desc": "Indicateur de mesure." },
  { "q": "nav", "desc": "Section de navigation." },
  { "q": "noscript", "desc": "Section à afficher lorsque les scripts sont désactivés." },
  { "q": "object", "desc": "Objet externe." },
  { "q": "ol", "desc": "Liste ordonnée." },
  { "q": "optgroup", "desc": "Groupe des options dans un élément de sélection." },
  { "q": "option", "desc": "Option dans un élément de sélection." },
  { "q": "output", "desc": "Résultat d'un calcul." },
  { "q": "p", "desc": "Paragraphe." },
  { "q": "param", "desc": "Paramètres pour un objet." },
  { "q": "picture", "desc": "Plusieurs éléments source pour différentes images." },
  { "q": "pre", "desc": "Texte préformaté." },
  { "q": "progress", "desc": "Barre de progression." },
  { "q": "q", "desc": "Courte citation en ligne." },
  { "q": "samp", "desc": "Sortie d'un programme informatique." },
  { "q": "script", "desc": "Code script, comme JavaScript." },
  { "q": "section", "desc": "Section thématique dans un document." },
  { "q": "select", "desc": "Liste déroulante." },
  { "q": "small", "desc": "Annotations ou texte secondaire." },
  { "q": "source", "desc": "Ressources média pour les éléments audio ou vidéo." },
  { "q": "span", "desc": "Conteneur en ligne générique." },
  { "q": "strong", "desc": "Texte important." },
  { "q": "style", "desc": "Styles pour le document." },
  { "q": "sub", "desc": "Texte en indice." },
  { "q": "summary", "desc": "Résumé pour un élément <details>." },
  { "q": "sup", "desc": "Texte en exposant." },
  { "q": "table", "desc": "Tableau de données." },
  { "q": "tbody", "desc": "Corps d'un tableau." },
  { "q": "td", "desc": "Cellule dans un tableau." },
  { "q": "template", "desc": "Contenu caché qui peut être affiché plus tard." },
  { "q": "textarea", "desc": "Zone de texte multiligne." },
  { "q": "tfoot", "desc": "Pied d'un tableau." },
  { "q": "th", "desc": "Cellule d'en-tête dans un tableau." },
  { "q": "thead", "desc": "En-tête d'un tableau." },
  { "q": "time", "desc": "Date ou une heure." },
  { "q": "title", "desc": "Titre du document." },
  { "q": "tr", "desc": "Rangée dans un tableau." },
  { "q": "track", "desc": "Pistes de texte pour les éléments audio ou vidéo." },
  { "q": "ul", "desc": "Liste non ordonnée." },
  { "q": "var", "desc": "Nom d'une variable." },
  { "q": "video", "desc": "Contenu vidéo." },
  { "q": "wbr", "desc": "Possibilité de passage à la ligne." }
];