// Réponses possibles des quiz JavaScript : nom, description, lien vers la documentation MDN
const js = 'https://developer.mozilla.org/fr/docs/Web/JavaScript/';
const api = 'https://developer.mozilla.org/fr/docs/Web/API/';

export default [
    // Les bases
    { name: 'const', desc: "Déclare une variable qui ne peut pas être réaffectée.", doc: `${js}Reference/Statements/const` },
    { name: 'let', desc: "Déclare une variable dont la valeur peut changer.", doc: `${js}Reference/Statements/let` },
    { name: 'if', desc: "Exécute un bloc seulement si une condition est vraie (avec else pour le cas contraire).", doc: `${js}Reference/Statements/if...else` },
    { name: 'for', desc: "Boucle avec un compteur : initialisation, condition, incrément.", doc: `${js}Reference/Statements/for` },
    { name: 'while', desc: "Boucle qui se répète tant qu'une condition est vraie.", doc: `${js}Reference/Statements/while` },
    { name: 'function', desc: "Déclare une fonction : un bloc de code réutilisable, avec des paramètres.", doc: `${js}Reference/Statements/function` },
    { name: 'return', desc: "Termine une fonction et renvoie une valeur à l'appelant.", doc: `${js}Reference/Statements/return` },
    { name: '=>', desc: "Fonction fléchée : une écriture courte des fonctions, très utilisée pour les écouteurs.", doc: `${js}Reference/Functions/Arrow_functions` },
    { name: 'console.log', desc: "Affiche une valeur dans la console des outils de développement.", doc: `${api}console/log_static` },
    { name: 'prompt', desc: "Ouvre une boîte de dialogue qui demande un texte à l'utilisateur.", doc: `${api}Window/prompt` },
    { name: 'typeof', desc: "Renvoie le type d'une valeur sous forme de texte : \"number\", \"string\"...", doc: `${js}Reference/Operators/typeof` },
    { name: '===', desc: "Égalité stricte : même valeur et même type.", doc: `${js}Reference/Operators/Strict_equality` },
    { name: '&&', desc: "ET logique : vrai si les deux conditions sont vraies.", doc: `${js}Reference/Operators/Logical_AND` },
    { name: '||', desc: "OU logique : vrai si au moins une des conditions est vraie.", doc: `${js}Reference/Operators/Logical_OR` },
    { name: '`${}`', desc: "Littéral de gabarit : une chaîne entre accents graves, qui insère des valeurs avec ${...}.", doc: `${js}Reference/Template_literals` },
    { name: 'parseInt', desc: "Lit un nombre entier au début d'une chaîne : parseInt(\"42px\") vaut 42.", doc: `${js}Reference/Global_Objects/parseInt` },
    { name: 'Number', desc: "Convertit une valeur en nombre, ou NaN si ce n'est pas un nombre.", doc: `${js}Reference/Global_Objects/Number` },
    { name: 'Math.random', desc: "Renvoie un nombre au hasard entre 0 (inclus) et 1 (exclu).", doc: `${js}Reference/Global_Objects/Math/random` },
    { name: 'Math.floor', desc: "Arrondit à l'entier inférieur.", doc: `${js}Reference/Global_Objects/Math/floor` },
    { name: 'Math.round', desc: "Arrondit à l'entier le plus proche.", doc: `${js}Reference/Global_Objects/Math/round` },
    { name: 'push', desc: "Ajoute un élément à la fin d'un tableau.", doc: `${js}Reference/Global_Objects/Array/push` },
    { name: 'length', desc: "Le nombre d'éléments d'un tableau (ou de caractères d'une chaîne).", doc: `${js}Reference/Global_Objects/Array/length` },
    { name: 'join', desc: "Rassemble les éléments d'un tableau en une seule chaîne, avec un séparateur.", doc: `${js}Reference/Global_Objects/Array/join` },
    { name: 'includes', desc: "Indique si un tableau contient une valeur (true ou false).", doc: `${js}Reference/Global_Objects/Array/includes` },
    { name: 'forEach', desc: "Exécute une fonction pour chaque élément d'un tableau.", doc: `${js}Reference/Global_Objects/Array/forEach` },
    { name: 'toUpperCase', desc: "Renvoie la chaîne en majuscules.", doc: `${js}Reference/Global_Objects/String/toUpperCase` },
    { name: 'trim', desc: "Renvoie la chaîne sans les espaces au début et à la fin.", doc: `${js}Reference/Global_Objects/String/trim` },

    // Le DOM
    { name: 'document', desc: "L'objet qui représente la page HTML chargée : le point d'entrée du DOM.", doc: `${api}Document` },
    { name: 'querySelector', desc: "Renvoie le premier élément qui correspond à un sélecteur CSS (ou null).", doc: `${api}Document/querySelector` },
    { name: 'querySelectorAll', desc: "Renvoie tous les éléments qui correspondent à un sélecteur CSS (une NodeList).", doc: `${api}Document/querySelectorAll` },
    { name: 'getElementById', desc: "Renvoie l'élément qui a cet id (sans le #).", doc: `${api}Document/getElementById` },
    { name: 'textContent', desc: "Le texte d'un élément, sans interpréter les balises HTML.", doc: `${api}Node/textContent` },
    { name: 'innerHTML', desc: "Le contenu HTML d'un élément : les balises sont interprétées.", doc: `${api}Element/innerHTML` },
    { name: 'value', desc: "La valeur saisie dans un champ de formulaire, toujours sous forme de texte.", doc: `${api}HTMLInputElement/value` },
    { name: 'dataset', desc: "Les attributs data-* d'un élément : data-color se lit avec dataset.color.", doc: `${api}HTMLElement/dataset` },
    { name: 'setAttribute', desc: "Donne une valeur à un attribut HTML d'un élément.", doc: `${api}Element/setAttribute` },
    { name: 'getAttribute', desc: "Lit la valeur d'un attribut HTML d'un élément.", doc: `${api}Element/getAttribute` },
    { name: 'hidden', desc: "Cache l'élément quand il vaut true (comme l'attribut HTML hidden).", doc: `${api}HTMLElement/hidden` },
    { name: 'disabled', desc: "Désactive un bouton ou un champ quand il vaut true.", doc: `${api}HTMLButtonElement/disabled` },
    { name: 'style', desc: "Les styles en ligne d'un élément : element.style.color = 'red'.", doc: `${api}HTMLElement/style` },
    { name: 'closest', desc: "Remonte les parents d'un élément jusqu'au premier qui correspond à un sélecteur.", doc: `${api}Element/closest` },
    { name: 'focus', desc: "Donne le focus à un élément (le curseur dans un champ, par exemple).", doc: `${api}HTMLElement/focus` },

    // Les événements
    { name: 'addEventListener', desc: "Associe une fonction à un événement d'un élément : on « écoute ».", doc: `${api}EventTarget/addEventListener` },
    { name: 'removeEventListener', desc: "Retire un écouteur d'événement : sa fonction ne sera plus appelée.", doc: `${api}EventTarget/removeEventListener` },
    { name: 'click', desc: "Événement déclenché quand on clique sur un élément.", doc: `${api}Element/click_event` },
    { name: 'input', desc: "Événement déclenché à chaque modification de la valeur d'un champ.", doc: `${api}Element/input_event` },
    { name: 'change', desc: "Événement déclenché quand la modification d'un champ est validée (perte du focus, case cochée...).", doc: `${api}HTMLElement/change_event` },
    { name: 'submit', desc: "Événement déclenché à l'envoi d'un formulaire.", doc: `${api}HTMLFormElement/submit_event` },
    { name: 'keydown', desc: "Événement déclenché quand une touche du clavier est enfoncée.", doc: `${api}Element/keydown_event` },
    { name: 'mousemove', desc: "Événement déclenché quand la souris bouge au-dessus d'un élément.", doc: `${api}Element/mousemove_event` },
    { name: 'DOMContentLoaded', desc: "Événement déclenché quand le HTML de la page est entièrement lu.", doc: `${api}Document/DOMContentLoaded_event` },
    { name: 'animationend', desc: "Événement déclenché à la fin d'une animation CSS.", doc: `${api}Element/animationend_event` },
    { name: 'transitionend', desc: "Événement déclenché à la fin d'une transition CSS.", doc: `${api}Element/transitionend_event` },
    { name: 'preventDefault', desc: "Empêche le comportement par défaut du navigateur (envoi du formulaire, suivi du lien...).", doc: `${api}Event/preventDefault` },
    { name: 'target', desc: "L'élément sur lequel l'événement s'est vraiment produit (parfois un enfant).", doc: `${api}Event/target` },
    { name: 'currentTarget', desc: "L'élément qui porte l'écouteur en cours d'exécution.", doc: `${api}Event/currentTarget` },
    { name: 'key', desc: "La touche du clavier concernée par l'événement : \"Enter\", \"ArrowLeft\", \"a\"...", doc: `${api}KeyboardEvent/key` },
    { name: 'clientX', desc: "La position horizontale de la souris, en pixels, dans la fenêtre.", doc: 'https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX' }, // pas de version française

    // Classes CSS et éléments
    { name: 'classList.add', desc: "Ajoute une classe CSS à un élément.", doc: `${api}DOMTokenList/add` },
    { name: 'classList.remove', desc: "Retire une classe CSS d'un élément.", doc: `${api}DOMTokenList/remove` },
    { name: 'classList.toggle', desc: "Ajoute la classe si elle est absente, la retire si elle est présente.", doc: `${api}DOMTokenList/toggle` },
    { name: 'classList.contains', desc: "Indique si l'élément a cette classe (true ou false).", doc: `${api}DOMTokenList/contains` },
    { name: 'classList.replace', desc: "Remplace une classe par une autre.", doc: `${api}DOMTokenList/replace` },
    { name: 'className', desc: "Toutes les classes de l'élément, en une seule chaîne : l'écraser retire les autres.", doc: `${api}Element/className` },
    { name: 'createElement', desc: "Crée un nouvel élément HTML, pas encore placé dans la page.", doc: `${api}Document/createElement` },
    { name: 'append', desc: "Ajoute des éléments (ou du texte) à la fin du contenu d'un élément.", doc: `${api}Element/append` },
    { name: 'prepend', desc: "Ajoute des éléments (ou du texte) au début du contenu d'un élément.", doc: `${api}Element/prepend` },
    { name: 'remove', desc: "Retire l'élément de la page.", doc: `${api}Element/remove` },
    { name: 'cloneNode', desc: "Crée une copie d'un élément (avec ses enfants si on passe true).", doc: `${api}Node/cloneNode` },
    { name: 'children', desc: "Les éléments enfants directs d'un élément.", doc: `${api}Element/children` },
    { name: 'insertAdjacentHTML', desc: "Insère du HTML écrit sous forme de texte, avant, après ou dans un élément.", doc: `${api}Element/insertAdjacentHTML` },
    { name: 'replaceChildren', desc: "Remplace tout le contenu d'un élément (sans argument : le vide).", doc: `${api}Element/replaceChildren` },

    // Le temps et l'animation
    { name: 'setTimeout', desc: "Exécute une fonction une seule fois, après un délai en millisecondes.", doc: `${api}Window/setTimeout` },
    { name: 'setInterval', desc: "Exécute une fonction de façon répétée, à intervalle régulier en millisecondes.", doc: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/setInterval' }, // pas de version française
    { name: 'clearTimeout', desc: "Annule une exécution différée qui ne s'est pas encore déclenchée.", doc: `${api}Window/clearTimeout` },
    { name: 'clearInterval', desc: "Arrête une exécution répétée à intervalle régulier.", doc: `${api}Window/clearInterval` },
    { name: 'requestAnimationFrame', desc: "Demande au navigateur d'appeler une fonction juste avant d'afficher la prochaine image.", doc: `${api}Window/requestAnimationFrame` },
    { name: 'cancelAnimationFrame', desc: "Annule l'appel prévu juste avant la prochaine image.", doc: `${api}Window/cancelAnimationFrame` },
    { name: 'Date.now', desc: "Le nombre de millisecondes écoulées depuis le 1er janvier 1970.", doc: `${js}Reference/Global_Objects/Date/now` },
    { name: 'localStorage.setItem', desc: "Enregistre une valeur dans le navigateur : elle reste après la fermeture de la page.", doc: `${api}Storage/setItem` },
    { name: 'localStorage.getItem', desc: "Lit une valeur enregistrée dans le navigateur (null si elle n'existe pas).", doc: `${api}Storage/getItem` },
    { name: 'localStorage.removeItem', desc: "Supprime une valeur enregistrée dans le navigateur.", doc: `${api}Storage/removeItem` },
    { name: 'JSON.stringify', desc: "Transforme un objet ou un tableau en texte JSON.", doc: `${js}Reference/Global_Objects/JSON/stringify` },
    { name: 'JSON.parse', desc: "Transforme un texte JSON en objet ou en tableau.", doc: `${js}Reference/Global_Objects/JSON/parse` },
    { name: 'matchMedia', desc: "Teste une media query depuis le JavaScript, par exemple prefers-reduced-motion.", doc: `${api}Window/matchMedia` },

    // Objets et classes
    { name: '{}', desc: "Objet littéral : un ensemble de paires propriété : valeur.", doc: `${js}Reference/Operators/Object_initializer` },
    { name: 'this', desc: "Dans une méthode, l'objet sur lequel la méthode est appelée.", doc: `${js}Reference/Operators/this` },
    { name: 'Object.keys', desc: "Renvoie le tableau des noms des propriétés d'un objet.", doc: `${js}Reference/Global_Objects/Object/keys` },
    { name: 'delete', desc: "Supprime une propriété d'un objet.", doc: `${js}Reference/Operators/delete` },
    { name: 'in', desc: "Indique si une propriété existe dans un objet : \"name\" in user.", doc: `${js}Reference/Operators/in` },
    { name: 'class', desc: "Déclare une classe : un modèle pour fabriquer des objets du même type.", doc: `${js}Reference/Statements/class` },
    { name: 'constructor', desc: "La méthode appelée à la création d'un objet, pour initialiser ses propriétés.", doc: `${js}Reference/Classes/constructor` },
    { name: 'new', desc: "Crée un objet à partir d'une classe : new Player().", doc: `${js}Reference/Operators/new` },
    { name: 'extends', desc: "Fait hériter une classe d'une autre : elle reprend ses propriétés et méthodes.", doc: `${js}Reference/Classes/extends` },
    { name: 'super', desc: "Appelle le constructeur ou une méthode de la classe parente.", doc: `${js}Reference/Operators/super` },
    { name: 'static', desc: "Déclare une méthode ou une propriété de la classe elle-même, pas de ses objets.", doc: `${js}Reference/Classes/static` },
    { name: 'get', desc: "Déclare un accesseur : une méthode qui se lit comme une propriété.", doc: `${js}Reference/Functions/get` },
    { name: 'set', desc: "Déclare un mutateur : une méthode appelée quand on affecte une propriété.", doc: `${js}Reference/Functions/set` },
    { name: '#', desc: "Préfixe d'un champ privé : inaccessible en dehors de la classe.", doc: `${js}Reference/Classes/Private_properties` },
    { name: 'instanceof', desc: "Indique si un objet a été créé à partir d'une classe (ou d'une classe fille).", doc: `${js}Reference/Operators/instanceof` },
    { name: 'prototype', desc: "L'objet partagé où JavaScript cherche les méthodes : les classes reposent dessus.", doc: `${js}Guide/Inheritance_and_the_prototype_chain` },
    { name: 'Object.create', desc: "Crée un objet en choisissant directement son prototype.", doc: `${js}Reference/Global_Objects/Object/create` },
    { name: '__proto__', desc: "Ancienne façon d'accéder au prototype d'un objet, à éviter dans le code récent.", doc: `${js}Reference/Global_Objects/Object/proto` }
];
